# yaml-language-server: $schema=https://raw.githubusercontent.com/neuro-inc/neuro-flow/refs/heads/master/src/apolo_flow/flow-schema.json
kind: live
title: {{ cookiecutter.flow_name }}

images:
  train:
    ref: image:/$[[ project.project_name ]]/$[[ flow.project_id ]]:v1
    dockerfile: $[[ flow.workspace ]]/Dockerfile
    context: $[[ flow.workspace ]]/


jobs:
  train:
    image: $[[ images.train.ref ]]
    bash: |
      echo Put your training code here
